package edu.ntnu.iir.bidata.ui;

import edu.ntnu.iir.bidata.model.DiaryEntry;
import org.junit.jupiter.api.Test;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/*
 * Tests have been partially generated by AI.
 */
public class FormatterTest {

  @Test
  void should_CreateALineOfCorrectLength_When_lineOfLengthIsCalled() {
    // Arrange:
    String message = "This string contains 34 characters";
    assertEquals(34, message.length());
    Formatter formatter = new Formatter();

    // Act:
    String lineOfNumber = formatter.line(20);
    String lineOfLengthMessage = formatter.line(message);

    // Assert:
    assertEquals(20 + "\n".length(), lineOfNumber.length());
    assertEquals(34 + "\n".length(), lineOfLengthMessage.length());
  }

  @Test
  void should_FormatListOfString_When_formatStringListIsCalled() {
    // Arrange:
    List<String> list = List.of("string0", "string1", "string2");
    Formatter formatter = new Formatter();

    // Act:
    String result = formatter.formatStringList(list);

    assertTrue(result.contains("3"));
    assertTrue(result.contains("string0"));
    assertTrue(result.contains("string1"));
    assertTrue(result.contains("string2"));

  }

  @Test
  void should_ReturnEmptyString_When_ListIsEmpty() {
    // Arrange:
    Formatter formatter = new Formatter();

    // Act:
    String result = formatter.formatStringList(List.of());

    // Assert:
    assertEquals("", result);
  }

  @Test
  void should_FormatListOfEntries_When_formatDiaryEntryListIsCalled() {
    // Arrange:
    DiaryEntry entry0 = new DiaryEntry("author0", "dest0", "act0", 0, "title0", "text0");
    List<DiaryEntry> listOfEntries = List.of(entry0);
    Formatter formatter = new Formatter();

    // Act:
    String result = formatter.formatDiaryEntryList(listOfEntries);

    // Assert:
    assertTrue(result.contains("author0"));
    assertTrue(result.contains("dest0"));
    assertTrue(result.contains("act0"));
    assertTrue(result.contains("title0"));
    assertFalse(result.contains("Index"));
  }

  @Test
  void should_FormatListOfEntriesWithIndex_When_formatDiaryEntryListIsCalled() {
    // Arrange:
    DiaryEntry entry0 = new DiaryEntry("author0", "dest0", "act0", 0, "title0", "text0");
    List<DiaryEntry> listOfEntries = List.of(entry0);
    Formatter formatter = new Formatter();

    // Act:
    String result = formatter.formatDiaryEntryIndexedList(listOfEntries);

    // Assert:
    assertTrue(result.contains("Index"));
    assertTrue(result.contains("author0"));
    assertTrue(result.contains("dest0"));
    assertTrue(result.contains("act0"));
    assertTrue(result.contains("title0"));
  }
}
